### ISSUE TITLE
Add russian locale

### ISSUE THREAD

**Issue by XakepSDK** [AntoineFr/flarum-ext-online#7]
`ru.yml`
```yml
antoinefr-online:
  forum:
    title: Кто онлайн?
  admin:
    settings:
      title: Настройки
      displaymax: Кол-во показываемых людей
```
